//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockPaper.Wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49207/api/V01/games?isActive={0}&teamId={1}&playAgainstSimulator" +
            "={2}")]
        public string GetNextAvailableGameLink {
            get {
                return ((string)(this["GetNextAvailableGameLink"]));
            }
            set {
                this["GetNextAvailableGameLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49207/api/V01/games/IsItMyTurn?gameId={0}&teamId={1}")]
        public string IsItMyTurnLink {
            get {
                return ((string)(this["IsItMyTurnLink"]));
            }
            set {
                this["IsItMyTurnLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49207/api/V01/games/PlayHand?gameId={0}&teamId={1}&hand={2}")]
        public string PlayHandLink {
            get {
                return ((string)(this["PlayHandLink"]));
            }
            set {
                this["PlayHandLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49207/api/V01/games/{0}")]
        public string GetGamebyGameIdLink {
            get {
                return ((string)(this["GetGamebyGameIdLink"]));
            }
            set {
                this["GetGamebyGameIdLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49207/api/V01/teams")]
        public string RegisterTeamLink {
            get {
                return ((string)(this["RegisterTeamLink"]));
            }
            set {
                this["RegisterTeamLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49207/api/V01/teams?teamName={0}")]
        public string GetTeamByTeamNameLink {
            get {
                return ((string)(this["GetTeamByTeamNameLink"]));
            }
            set {
                this["GetTeamByTeamNameLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49207/api/V01/rounds?gameId={0}")]
        public string GetCompletedRoundByGameIdLink {
            get {
                return ((string)(this["GetCompletedRoundByGameIdLink"]));
            }
            set {
                this["GetCompletedRoundByGameIdLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayAgainstSimulator {
            get {
                return ((bool)(this["PlayAgainstSimulator"]));
            }
            set {
                this["PlayAgainstSimulator"] = value;
            }
        }
    }
}
